#!/usr/bin/env bash
file=$1
w=$2
h=$3
x=$4
y=$5


mimetype=$(file -Lb --mime-type $1)

if [[ "${mimetype}" =~ ^image ]]; then
    kitty +icat --silent --transfer-mode file --place "${w}x${h}@${x}x${y}" "$file"
    exit 1
fi

pistol "$file"

