#!/bin/bash
set -e
COMMIT_MSG_FILE=$1
COMMIT_TYPE=$2
COMMIT_HASH=$3

# in case of rebasing there is no symbolic ref for current HEAD
# therefore we can abort further steps
BRANCH_NAME=$(git symbolic-ref --short HEAD) || exit 0
BRANCH_REGEX="^(feature|bugfix|task|fault|fix)/([A-Za-z]+-[0-9]+).*$"
TEMP_FILE=/tmp/commit

meta_prefix() {
    case $1 in
        feature)
            echo "Adds"
            ;;
        bugfix|fault|fix)
            echo "Fixes"
            ;;
        task)
            echo "Resolves"
            ;;
    esac
}

get_ocurrences() {
  echo $(grep -c "\[${1}\]" ${COMMIT_MSG_FILE})
}

if [[ $BRANCH_NAME =~ $BRANCH_REGEX ]]; then
    issue_type=${BASH_REMATCH[1]}
    issue_number=${BASH_REMATCH[2]}
    issue_ocurrences=$(get_ocurrences $issue_number)

    if [[ $issue_ocurrences != "0" ]]; then
        exit 0
    fi

    prefix=$(meta_prefix $issue_type)

    if [ -z $prefix ]; then
        issue_marker="${prefix}: [${issue_number}]"
    else
        issue_marker="[${issue_number}]"
    fi


    printf "\n\n${issue_marker}" > $TEMP_FILE
    cat $COMMIT_MSG_FILE >> $TEMP_FILE
    cat $TEMP_FILE > $COMMIT_MSG_FILE
fi
