#!/bin/sh
set -e

TMP_TAGS=/tmp/tags
LOCAL_TAGS="${PWD}/.tags"

git ls-files | \
  ctags -L - -f "${TMP_TAGS}"

if [ -n $VIRTUAL_ENV ]
then
  find $VIRTUAL_ENV/lib/python* -name "*.py" | \
    ctags --exclude="**/IPython/*" -L - \
      --append=yes \
      -f "${TMP_TAGS}"
fi
mv "${TMP_TAGS}" "${LOCAL_TAGS}"

