#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files | \
  ctags --tag-relative -L - -f"$dir/$$.tags"

if [ -n $VIRTUAL_ENV ]
then
  find $VIRTUAL_ENV/lib/python* -name "*.py" | \
  ctags --exclude="**/IPython/*" --tag-relative -L - --append=yes -f"$dir/$$.tags"
fi
mv "$dir/$$.tags" "$dir/tags"

