#!/bin/bash
set -e
COMMIT_MSG_FILE=$1
COMMIT_TYPE=$2
COMMIT_HASH=$3

BRANCH_NAME=$(git symbolic-ref --short HEAD)
BRANCH_REGEX="^(feature|bugfix|task|fault)/([A-Za-z]+-[0-9]+).*$"

meta_prefix() {
    case $1 in
        feature)
            echo "Adds"
            ;;
        bugfix|fault)
            echo "Fixes"
            ;;
        task)
            echo "Resolves"
            ;;
    esac
}

get_ocurrences() {
  echo $(grep -c "\[${1}\]" ${COMMIT_MSG_FILE})
}

if [[ $BRANCH_NAME =~ $BRANCH_REGEX ]]; then
    issue_type=${BASH_REMATCH[1]}
    issue_number=${BASH_REMATCH[2]}
    issue_ocurrences=$(get_ocurrences $issue_number)

    if [[ $issue_ocurrences != "0" ]]; then
        exit 0
    fi

    prefix=$(meta_prefix $issue_type)

    issue_marker="${prefix}: [${issue_number}]"

    echo >> $COMMIT_MSG_FILE
    echo $issue_marker >> $COMMIT_MSG_FILE
fi
